import 'package:flutter/foundation.dart';

/// Daily aggregated step record.
///
/// Hand-written immutable value object intentionally mirroring the shape
/// generated by `freezed` so it can be migrated later by adding the
/// annotation without breaking call sites. We keep this hand-rolled to
/// avoid a hard dependency on `build_runner` for this data layer.
///
/// `source` identifies origin (pedometer / health_kit / health_connect /
/// manual / fallback) and is used for cross-device dedupe along with
/// [date].
@immutable
class DailyStep {
  const DailyStep({
    required this.date,
    required this.steps,
    this.distanceMeters = 0,
    this.calories = 0,
    this.activeMinutes = 0,
    this.source = DailyStepSource.pedometer,
    this.updatedAt,
  });

  factory DailyStep.fromJson(Map<String, Object?> json) {
    return DailyStep(
      date: DateTime.parse(json['date']! as String),
      steps: (json['steps']! as num).toInt(),
      distanceMeters: ((json['distance_m'] ?? 0) as num).toDouble(),
      calories: ((json['calories'] ?? 0) as num).toDouble(),
      activeMinutes: ((json['active_minutes'] ?? 0) as num).toInt(),
      source: DailyStepSource.values.firstWhere(
        (DailyStepSource s) => s.name == (json['source'] ?? 'pedometer'),
        orElse: () => DailyStepSource.pedometer,
      ),
      updatedAt: json['updated_at'] == null
          ? null
          : DateTime.parse(json['updated_at']! as String),
    );
  }

  /// Local midnight (start of day). Acts as the primary key for the row.
  final DateTime date;
  final int steps;
  final double distanceMeters;
  final double calories;
  final int activeMinutes;
  final DailyStepSource source;
  final DateTime? updatedAt;

  /// Convenience: stride-derived distance (in meters) if [distanceMeters]
  /// is zero. Average stride ~0.762 m for adults.
  double get estimatedDistanceMeters =>
      distanceMeters > 0 ? distanceMeters : steps * 0.762;

  DailyStep copyWith({
    DateTime? date,
    int? steps,
    double? distanceMeters,
    double? calories,
    int? activeMinutes,
    DailyStepSource? source,
    DateTime? updatedAt,
  }) {
    return DailyStep(
      date: date ?? this.date,
      steps: steps ?? this.steps,
      distanceMeters: distanceMeters ?? this.distanceMeters,
      calories: calories ?? this.calories,
      activeMinutes: activeMinutes ?? this.activeMinutes,
      source: source ?? this.source,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  Map<String, Object?> toJson() {
    return <String, Object?>{
      'date': _dateOnly(date).toIso8601String(),
      'steps': steps,
      'distance_m': distanceMeters,
      'calories': calories,
      'active_minutes': activeMinutes,
      'source': source.name,
      if (updatedAt != null) 'updated_at': updatedAt!.toIso8601String(),
    };
  }

  static DateTime _dateOnly(DateTime d) => DateTime(d.year, d.month, d.day);

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is DailyStep &&
        other.date.year == date.year &&
        other.date.month == date.month &&
        other.date.day == date.day &&
        other.steps == steps &&
        other.distanceMeters == distanceMeters &&
        other.calories == calories &&
        other.activeMinutes == activeMinutes &&
        other.source == source;
  }

  @override
  int get hashCode => Object.hash(
        date.year,
        date.month,
        date.day,
        steps,
        distanceMeters,
        calories,
        activeMinutes,
        source,
      );

  @override
  String toString() =>
      'DailyStep(date: $date, steps: $steps, source: ${source.name})';
}

enum DailyStepSource {
  pedometer,
  healthKit,
  healthConnect,
  manual,
  fallback,
}
